### ISSUE TITLE
URI Error

### ISSUE THREAD

**Issue by wernerstucky** [pm2-hive/pm2-mongodb#13]
I'm getting this error when trying to use pm2-mongodb

8|pm2-mong | URIError: URI malformed
8|pm2-mong |     at decodeURIComponent (native)
8|pm2-mong |     at Url.parse (url.js:269:19)
8|pm2-mong |     at Object.urlParse [as parse] (url.js:75:5)
8|pm2-mong |     at module.exports (/root/.pm2/node_modules/mongodb/lib/url_parser.js:16:23)
8|pm2-mong |     at connect (/root/.pm2/node_modules/mongodb/lib/mongo_client.js:486:16)
8|pm2-mong |     at /root/.pm2/node_modules/mongodb/lib/mongo_client.js:240:7
8|pm2-mong |     at Function.MongoClient.connect (/root/.pm2/node_modules/mongodb/lib/mongo_client.js:236:12)
8|pm2-mong |     at Object.init (/root/.pm2/node_modules/pm2-mongodb/lib/stats/client.js:53:15)
8|pm2-mong |     at Object.init (/root/.pm2/node_modules/pm2-mongodb/lib/stats/index.js:78:12)
8|pm2-mong |     at /root/.pm2/node_modules/pm2-mongodb/app.js:33:9
8|pm2-mong | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

**Comment by bcbee** [comment]
I have the same issue on Debian 8 and MongoDB 3.6
